# Generated by Django 4.1.5 on 2024-01-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_itemcarrinho_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='status',
        ),
        migrations.AddField(
            model_name='carrinho',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='finalizado',
            field=models.BooleanField(default=True),
        ),
    ]
